### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by vsreekanti** [ground-context/ground#16]
Document all the external facing APIs and use something like [Swagger](http://swagger.io/) to automatically generate API docs for us.

**Comment by tarpdalton** [comment]
For storing/displaying ground's documentation, we can create github pages by storing them in the docs folder on the master branch.
[Publish Your Project Documentation with GitHub Pages](https://github.com/blog/2233-publish-your-project-documentation-with-github-pages)

**Comment by vsreekanti** [comment]
@tarpdalton With the Swagger implementation, is it possible to have the framework generate standalone HTML files? If so, could we separate that code out for #19?

**Comment by vsreekanti** [comment]
http://www.ground-context.org/ground/api/ Any idea why this is happening?

**Comment by tarpdalton** [comment]
It is because the request (to get the JSON) is from ground-context.org not ground-context.github.io/ground/api. I might be able to change the CORS setting or something to allow cross origin requests

**Comment by tarpdalton** [comment]
I'll see if I can fix it with Crossorigin.me or cors.io Since GitHub has cors disabled

**Comment by vsreekanti** [comment]
Great, thanks James!
