### ISSUE TITLE
config.ini for github plugin wrong in docker image

### ISSUE THREAD

**Issue by epaulson** [ground-context/ground#37]
The getting started wiki page makes it pretty easy to get started with - however, there's a slight hiccup with the docker images and the github plugin image (the one that runs 'python parsegitlog.py')

the config.ini file for kafka and ground services both point to localhost, but in the docker setup they're linked to 'kafka' and 'ground' for hostnames. Once I exec'ed into the image and fixed the config file it worked.

Without it, you'll get an error like so:

docker logs ea212d2e6ad9
Traceback (most recent call last):
  File "parsegitlog.py", line 121, in <module>
    bootstrap_servers=[config['Kafka']['url'] + ":" + config['Kafka']['port']])
  File "/usr/local/lib/python3.5/site-packages/kafka/consumer/group.py", line 284, in __init__
    self._client = KafkaClient(metrics=self._metrics, **self.config)
  File "/usr/local/lib/python3.5/site-packages/kafka/client_async.py", line 202, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/usr/local/lib/python3.5/site-packages/kafka/client_async.py", line 791, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable

**Comment by tarpdalton** [comment]
I updated the docker image on dockerhub. I must have pushed an image with the wrong configs. I am working on testing it right now to make sure its working right.
https://hub.docker.com/r/groundcontext/git/tags/

**Comment by epaulson** [comment]
Thanks. I pulled the latest docker image and it's not immediately exiting, so I think that's a good sign.
