### ISSUE TITLE
post experiments from CIDR paper?

### ISSUE THREAD

**Issue by epaulson** [ground-context/ground#40]
It'd be very helpful to get a sense of an application using ground. Maybe it'd be possible to post the code for the impact analysis experiment? That looks like it's not terribly complicated on external dependencies and should be easy to interpret.

**Comment by vsreekanti** [comment]
Great idea! I have a bunch of files all over the place. I'll try to aggregate and make things presentable.

**Comment by vsreekanti** [comment]
Sorry for not following up on this sooner. We're going to have some more interesting / better flushed out use cases in the next month or so; I'm going to close this because we'll just post those instead.

Thanks again for the idea!
