### ISSUE TITLE
Wrong ports in instructions on DockerHub

### ISSUE THREAD

**Issue by jankneumann** [ground-context/ground#64]
Hi,

this is really interesting work. I was just playing with the Docker containers and noticed that the example for running the code here https://hub.docker.com/r/groundcontext/ground/ states that the open port should be 8080, but in reality it should be 9090 and 9191.

docker run -d --rm --name ground -p 9090:9090 -p 9191:9191 --link neo:neo groundcontext/ground

Cheers, Jan

**Comment by vsreekanti** [comment]
Thanks for pointing this out, Jan. A lot of this stuff should be changing soon, so we'll make sure to clean that up!
