### ISSUE TITLE
Pom.xml removed; build instructions deprecated

### ISSUE THREAD

**Issue by gharman** [ground-context/ground#78]
The pom.xml file was removed in commit 59599819edd3932e05472fa4bef0dd7f7da4a920 breaking the maven build instructions in the readme and on ground-context.org.

I see sbt artifacts in the project - if a switch to sbt was intentional then the documentation needs to be updated; else pom.xml should be put back.

**Comment by kevinji** [comment]
I believe a switch to sbt is intentional, but pinging @vsreekanti just to be sure.

**Comment by vsreekanti** [comment]
Sorry for the inconsistency, @gharman. We're in a state of high flux right now, and a couple things have slipped through the cracks. I'll update the build instructions on the website ASAP.
