### ISSUE TITLE
CIDR17.pdf paper is not accessible.

### ISSUE THREAD

**Issue by dmoore247** [ground-context/ground#94]
The wiki page [https://github.com/ground-context/ground/wiki] links to https://github.com/ground-context/ground/blob/master/CIDR17.pdf and returns Github's 404 page.

**Comment by tarpdalton** [comment]
Here is the link on CIDR's website: http://cidrdb.org/cidr2017/papers/p111-hellerstein-cidr17.pdf

**Comment by vsreekanti** [comment]
@tarpdalton's link is correct (thanks, James!). The Wiki is also outdated -- I just forgot to turn it off. The new wiki can be found [here](http://www.ground-context.org/wiki).
